echo copying rwgtex-dds.exe...
copy ..\rwgtex.exe ..\rwgtex-dds.exe /Y >> garbage

echo copying rwgtex-dds-ati.exe...
copy ..\rwgtex.exe ..\rwgtex-dds-ati.exe /Y >> garbage

echo copying rwgtex-dds-nv.exe...
copy ..\rwgtex.exe ..\rwgtex-dds-nv.exe /Y >> garbage

echo copying rwgtex-dds-nomip.exe...
copy ..\rwgtex.exe ..\rwgtex-dds-nomip.exe /Y >> garbage

echo copying rwgtex-dds-npot.exe...
copy ..\rwgtex.exe ..\rwgtex-dds-npot.exe /Y >> garbage

echo copying rwgtex-dds-npot-2x.exe...
copy ..\rwgtex.exe ..\rwgtex-dds-npot-2x.exe /Y >> garbage

echo copying rwgtex-dds-bgra.exe...
copy ..\rwgtex.exe ..\rwgtex-dds-bgra.exe /Y >> garbage

echo copying rwgtex-dds-ycg1.exe...
copy ..\rwgtex.exe ..\rwgtex-dds-ycg1.exe /Y >> garbage

echo copying rwgtex-dds-ycg2.exe...
copy ..\rwgtex.exe ..\rwgtex-dds-ycg2.exe /Y >> garbage

del garbage /Q